/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Personaje;
import Clases.armas;
import Controlador.Iniciador;

/**
 *
 * @author José Fernando Chan
 */
public class ListaPersonajes extends javax.swing.JFrame {

    
    //Variable que sirve para saber en que posición se debe agregar al personaje
    private int posicionPersonaje;
    
    //Variable para actualizar el frame de "EleccionPersonajes"
    private EleccionPersonajes FRMEleccionPersonajes;
    
    
    //Se modifico el codigo para que requiera como parametros la posicionPersonaje y FRMEleccionPersonajes
    public ListaPersonajes(int posicionPersonaje, EleccionPersonajes FRMEleccionPersonajes) {
        initComponents();
        botonesTransparentes();
        this.posicionPersonaje = posicionPersonaje;
        this.FRMEleccionPersonajes = FRMEleccionPersonajes;
    }
    
    //Metodo para botones transparentes
    public void botonesTransparentes(){
    JBBarbara.setOpaque(false);
    JBBarbara.setContentAreaFilled(false);
    JBBarbara.setBorderPainted(false);
    
    JBBeidou.setOpaque(false);
    JBBeidou.setContentAreaFilled(false);
    JBBeidou.setBorderPainted(false);
    
    JBChongyun.setOpaque(false);
    JBChongyun.setContentAreaFilled(false);
    JBChongyun.setBorderPainted(false);
    
    JBDiluc.setOpaque(false);
    JBDiluc.setContentAreaFilled(false);
    JBDiluc.setBorderPainted(false);
    
    JBFischl.setOpaque(false);
    JBFischl.setContentAreaFilled(false);
    JBFischl.setBorderPainted(false);
    
    JBKeqing.setOpaque(false);
    JBKeqing.setContentAreaFilled(false);
    JBKeqing.setBorderPainted(false);
    
    JBMona.setOpaque(false);
    JBMona.setContentAreaFilled(false);
    JBMona.setBorderPainted(false);
    
    JBQiqi.setOpaque(false);
    JBQiqi.setContentAreaFilled(false);
    JBQiqi.setBorderPainted(false);
    
    JBSucrose.setOpaque(false);
    JBSucrose.setContentAreaFilled(false);
    JBSucrose.setBorderPainted(false);
    
    JBVenti.setOpaque(false);
    JBVenti.setContentAreaFilled(false);
    JBVenti.setBorderPainted(false);
    
    JBXiangling.setOpaque(false);
    JBXiangling.setContentAreaFilled(false);
    JBXiangling.setBorderPainted(false);
    
    JBZhongli.setOpaque(false);
    JBZhongli.setContentAreaFilled(false);
    JBZhongli.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBBarbara = new javax.swing.JButton();
        JBBeidou = new javax.swing.JButton();
        JBChongyun = new javax.swing.JButton();
        JBDiluc = new javax.swing.JButton();
        JBSucrose = new javax.swing.JButton();
        JBFischl = new javax.swing.JButton();
        JBKeqing = new javax.swing.JButton();
        JBMona = new javax.swing.JButton();
        JBQiqi = new javax.swing.JButton();
        JBVenti = new javax.swing.JButton();
        JBXiangling = new javax.swing.JButton();
        JBZhongli = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBBarbara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Avatares/Barbara-Icon.png"))); // NOI18N
        JBBarbara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBBarbaraMouseClicked(evt);
            }
        });
        getContentPane().add(JBBarbara, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 130, 130));

        JBBeidou.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Avatares/Beidou-Icon.png"))); // NOI18N
        JBBeidou.setMinimumSize(new java.awt.Dimension(161, 137));
        JBBeidou.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBBeidouMouseClicked(evt);
            }
        });
        getContentPane().add(JBBeidou, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 130, 130));

        JBChongyun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Avatares/Chongyun-Icon.png"))); // NOI18N
        JBChongyun.setMinimumSize(new java.awt.Dimension(161, 137));
        JBChongyun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBChongyunMouseClicked(evt);
            }
        });
        getContentPane().add(JBChongyun, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 130, 130));

        JBDiluc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Avatares/Diluc-Icon.png"))); // NOI18N
        JBDiluc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBDilucMouseClicked(evt);
            }
        });
        getContentPane().add(JBDiluc, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 130, 130));

        JBSucrose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Avatares/Sucrose-Icon.png"))); // NOI18N
        JBSucrose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBSucroseMouseClicked(evt);
            }
        });
        getContentPane().add(JBSucrose, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 130, 130));

        JBFischl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Avatares/Fischl-Icon.png"))); // NOI18N
        JBFischl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBFischlMouseClicked(evt);
            }
        });
        getContentPane().add(JBFischl, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 130, 130));

        JBKeqing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Avatares/Keqing-Icon.png"))); // NOI18N
        JBKeqing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBKeqingMouseClicked(evt);
            }
        });
        getContentPane().add(JBKeqing, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 130, 130));

        JBMona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Avatares/Mona-Icon.png"))); // NOI18N
        JBMona.setPreferredSize(new java.awt.Dimension(161, 137));
        JBMona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBMonaMouseClicked(evt);
            }
        });
        getContentPane().add(JBMona, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 130, 130));

        JBQiqi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Avatares/Qiqi-Icon.png"))); // NOI18N
        JBQiqi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBQiqiMouseClicked(evt);
            }
        });
        getContentPane().add(JBQiqi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 130, 130));

        JBVenti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Avatares/Venti-Icon.png"))); // NOI18N
        JBVenti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBVentiMouseClicked(evt);
            }
        });
        getContentPane().add(JBVenti, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 130, 130));

        JBXiangling.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Avatares/Xiangling-Icon.png"))); // NOI18N
        JBXiangling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBXianglingMouseClicked(evt);
            }
        });
        getContentPane().add(JBXiangling, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 130, 130));

        JBZhongli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Avatares/Zhongli-Icon.png"))); // NOI18N
        JBZhongli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBZhongliMouseClicked(evt);
            }
        });
        getContentPane().add(JBZhongli, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, 130, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/screen-5.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBBarbaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBBarbaraMouseClicked
        // TODO add your handling code here:
        Iniciador.equipo[posicionPersonaje] = new Personaje("Barbara", new armas(),"Guia de la libertad");
        FRMEleccionPersonajes.repaint();
        this.dispose();
    }//GEN-LAST:event_JBBarbaraMouseClicked

    private void JBBeidouMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBBeidouMouseClicked
        // TODO add your handling code here:
        Iniciador.equipo[posicionPersonaje] = new Personaje("Beidou", new armas(),"Guia del oro");
        FRMEleccionPersonajes.repaint();
        this.dispose();
    }//GEN-LAST:event_JBBeidouMouseClicked

    private void JBChongyunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBChongyunMouseClicked
        // TODO add your handling code here:
        Iniciador.equipo[posicionPersonaje] = new Personaje("Chongyun", new armas(),"Guia de la diligencia");
        FRMEleccionPersonajes.repaint();
        this.dispose();
    }//GEN-LAST:event_JBChongyunMouseClicked

    private void JBDilucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBDilucMouseClicked
        // TODO add your handling code here:
        Iniciador.equipo[posicionPersonaje] = new Personaje("Diluc", new armas(),"Guia de la resistencia");
        FRMEleccionPersonajes.repaint();
        this.dispose();
    }//GEN-LAST:event_JBDilucMouseClicked

    private void JBSucroseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBSucroseMouseClicked
        // TODO add your handling code here:
        Iniciador.equipo[posicionPersonaje] = new Personaje("Sucrose", new armas(),"Guia de la libertad");
        FRMEleccionPersonajes.repaint();
        this.dispose();
    }//GEN-LAST:event_JBSucroseMouseClicked

    private void JBFischlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBFischlMouseClicked
        // TODO add your handling code here:
        Iniciador.equipo[posicionPersonaje] = new Personaje("Fischl", new armas(),"Guia de la poesia");
        FRMEleccionPersonajes.repaint();
        this.dispose();
    }//GEN-LAST:event_JBFischlMouseClicked

    private void JBKeqingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBKeqingMouseClicked
        // TODO add your handling code here:
        Iniciador.equipo[posicionPersonaje] = new Personaje("Keqing", new armas(),"Guia de la prosperidad");
        FRMEleccionPersonajes.repaint();
        this.dispose();
    }//GEN-LAST:event_JBKeqingMouseClicked

    private void JBMonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBMonaMouseClicked
        // TODO add your handling code here:
        Iniciador.equipo[posicionPersonaje] = new Personaje("Mona", new armas(),"Guia de la resistencia");
        FRMEleccionPersonajes.repaint();
        this.dispose();
    }//GEN-LAST:event_JBMonaMouseClicked

    private void JBQiqiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBQiqiMouseClicked
        // TODO add your handling code here:
        Iniciador.equipo[posicionPersonaje] = new Personaje("Qiqi", new armas(),"Guia de la prosperidad");
        FRMEleccionPersonajes.repaint();
        this.dispose();
    }//GEN-LAST:event_JBQiqiMouseClicked

    private void JBVentiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBVentiMouseClicked
        // TODO add your handling code here:
        Iniciador.equipo[posicionPersonaje] = new Personaje("Venti", new armas(),"Guia de la poesia");
        FRMEleccionPersonajes.repaint();
        this.dispose();
    }//GEN-LAST:event_JBVentiMouseClicked

    private void JBXianglingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBXianglingMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        Iniciador.equipo[posicionPersonaje] = new Personaje("Xiangling", new armas(),"Guia de la diligencia");
        FRMEleccionPersonajes.repaint();
        this.dispose();
    }//GEN-LAST:event_JBXianglingMouseClicked

    private void JBZhongliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBZhongliMouseClicked
        // TODO add your handling code here:
        Iniciador.equipo[posicionPersonaje] = new Personaje("Zhongli", new armas(),"Guia del oro");
        FRMEleccionPersonajes.repaint();
        this.dispose();
    }//GEN-LAST:event_JBZhongliMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBBarbara;
    private javax.swing.JButton JBBeidou;
    private javax.swing.JButton JBChongyun;
    private javax.swing.JButton JBDiluc;
    private javax.swing.JButton JBFischl;
    private javax.swing.JButton JBKeqing;
    private javax.swing.JButton JBMona;
    private javax.swing.JButton JBQiqi;
    private javax.swing.JButton JBSucrose;
    private javax.swing.JButton JBVenti;
    private javax.swing.JButton JBXiangling;
    private javax.swing.JButton JBZhongli;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
