/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author José Fernando Chan
 */
public class ListaPersonajes extends javax.swing.JFrame {

    /**
     * Creates new form ListaPersonajes
     */
    public ListaPersonajes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btElec1 = new java.awt.Button();
        btEle2 = new java.awt.Button();
        btEle3 = new java.awt.Button();
        btEle4 = new java.awt.Button();
        btEle5 = new java.awt.Button();
        btEle6 = new java.awt.Button();
        btEle7 = new java.awt.Button();
        btEle8 = new java.awt.Button();
        btEle9 = new java.awt.Button();
        btEle10 = new java.awt.Button();
        btEle11 = new java.awt.Button();
        btEle12 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btElec1.setLabel("button1");
        btElec1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btElec1ActionPerformed(evt);
            }
        });
        getContentPane().add(btElec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        btEle2.setLabel("button1");
        btEle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEle2ActionPerformed(evt);
            }
        });
        getContentPane().add(btEle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        btEle3.setLabel("button1");
        btEle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEle3ActionPerformed(evt);
            }
        });
        getContentPane().add(btEle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        btEle4.setLabel("button1");
        btEle4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEle4ActionPerformed(evt);
            }
        });
        getContentPane().add(btEle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, -1, -1));

        btEle5.setLabel("button1");
        btEle5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEle5ActionPerformed(evt);
            }
        });
        getContentPane().add(btEle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        btEle6.setLabel("button1");
        btEle6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEle6ActionPerformed(evt);
            }
        });
        getContentPane().add(btEle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        btEle7.setLabel("button1");
        btEle7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEle7ActionPerformed(evt);
            }
        });
        getContentPane().add(btEle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));

        btEle8.setLabel("button1");
        btEle8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEle8ActionPerformed(evt);
            }
        });
        getContentPane().add(btEle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, -1, -1));

        btEle9.setLabel("button1");
        btEle9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEle9ActionPerformed(evt);
            }
        });
        getContentPane().add(btEle9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        btEle10.setLabel("button1");
        btEle10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEle10ActionPerformed(evt);
            }
        });
        getContentPane().add(btEle10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, -1));

        btEle11.setLabel("button1");
        btEle11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEle11ActionPerformed(evt);
            }
        });
        getContentPane().add(btEle11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, -1));

        btEle12.setLabel("button1");
        btEle12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEle12ActionPerformed(evt);
            }
        });
        getContentPane().add(btEle12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/screen-5.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btElec1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btElec1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btElec1ActionPerformed

    private void btEle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEle2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEle2ActionPerformed

    private void btEle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEle3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEle3ActionPerformed

    private void btEle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEle4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEle4ActionPerformed

    private void btEle5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEle5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEle5ActionPerformed

    private void btEle6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEle6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEle6ActionPerformed

    private void btEle7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEle7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEle7ActionPerformed

    private void btEle8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEle8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEle8ActionPerformed

    private void btEle9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEle9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEle9ActionPerformed

    private void btEle10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEle10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEle10ActionPerformed

    private void btEle11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEle11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEle11ActionPerformed

    private void btEle12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEle12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEle12ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btEle10;
    private java.awt.Button btEle11;
    private java.awt.Button btEle12;
    private java.awt.Button btEle2;
    private java.awt.Button btEle3;
    private java.awt.Button btEle4;
    private java.awt.Button btEle5;
    private java.awt.Button btEle6;
    private java.awt.Button btEle7;
    private java.awt.Button btEle8;
    private java.awt.Button btEle9;
    private java.awt.Button btElec1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
