/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author José Fernando Chan
 */
public class ListaPersonajes extends javax.swing.JFrame {

    
    //Variable que sirve para saber en que posición se debe agregar al personaje
    private int posicionPersonaje;
    
    //Variable para actualizar el frame de "EleccionPersonajes"
    private EleccionPersonajes FRMEleccionPersonajes;
    
    
    //Se modifico el codigo para que requiera como parametros la posicionPersonaje y FRMEleccionPersonajes
    public ListaPersonajes(int posicionPersonaje, EleccionPersonajes FRMEleccionPersonajes) {
        initComponents();
        botonesTransparentes();
        this.posicionPersonaje = posicionPersonaje;
        this.FRMEleccionPersonajes = FRMEleccionPersonajes;
    }
    
    //Metodo para botones transparentes
    public void botonesTransparentes(){
    JBBarbara.setOpaque(false);
    JBBarbara.setContentAreaFilled(false);
    JBBarbara.setBorderPainted(false);
    
    JBBeidou.setOpaque(false);
    JBBeidou.setContentAreaFilled(false);
    JBBeidou.setBorderPainted(false);
    
    JBChongyun.setOpaque(false);
    JBChongyun.setContentAreaFilled(false);
    JBChongyun.setBorderPainted(false);
    
    JBDiluc.setOpaque(false);
    JBDiluc.setContentAreaFilled(false);
    JBDiluc.setBorderPainted(false);
    
    JBFischl.setOpaque(false);
    JBFischl.setContentAreaFilled(false);
    JBFischl.setBorderPainted(false);
    
    JBKeqing.setOpaque(false);
    JBKeqing.setContentAreaFilled(false);
    JBKeqing.setBorderPainted(false);
    
    JBMona.setOpaque(false);
    JBMona.setContentAreaFilled(false);
    JBMona.setBorderPainted(false);
    
    JBQiqi.setOpaque(false);
    JBQiqi.setContentAreaFilled(false);
    JBQiqi.setBorderPainted(false);
    
    JBSucrose.setOpaque(false);
    JBSucrose.setContentAreaFilled(false);
    JBSucrose.setBorderPainted(false);
    
    JBVenti.setOpaque(false);
    JBVenti.setContentAreaFilled(false);
    JBVenti.setBorderPainted(false);
    
    JBXiangling.setOpaque(false);
    JBXiangling.setContentAreaFilled(false);
    JBXiangling.setBorderPainted(false);
    
    jButton12.setOpaque(false);
    jButton12.setContentAreaFilled(false);
    jButton12.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBBarbara = new javax.swing.JButton();
        JBBeidou = new javax.swing.JButton();
        JBChongyun = new javax.swing.JButton();
        JBDiluc = new javax.swing.JButton();
        JBSucrose = new javax.swing.JButton();
        JBFischl = new javax.swing.JButton();
        JBKeqing = new javax.swing.JButton();
        JBMona = new javax.swing.JButton();
        JBQiqi = new javax.swing.JButton();
        JBVenti = new javax.swing.JButton();
        JBXiangling = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBBarbara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Avatares/Barbara-Icon.png"))); // NOI18N
        JBBarbara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBBarbaraMouseClicked(evt);
            }
        });
        JBBarbara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBarbaraActionPerformed(evt);
            }
        });
        getContentPane().add(JBBarbara, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 130, 130));

        JBBeidou.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Avatares/Beidou-Icon.png"))); // NOI18N
        JBBeidou.setMinimumSize(new java.awt.Dimension(161, 137));
        JBBeidou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBeidouActionPerformed(evt);
            }
        });
        getContentPane().add(JBBeidou, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 130, 130));

        JBChongyun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Avatares/Chongyun-Icon.png"))); // NOI18N
        JBChongyun.setMinimumSize(new java.awt.Dimension(161, 137));
        getContentPane().add(JBChongyun, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 130, 130));

        JBDiluc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Avatares/Diluc-Icon.png"))); // NOI18N
        getContentPane().add(JBDiluc, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 130, 130));

        JBSucrose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Avatares/Sucrose-Icon.png"))); // NOI18N
        getContentPane().add(JBSucrose, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 130, 130));

        JBFischl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Avatares/Fischl-Icon.png"))); // NOI18N
        JBFischl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBFischlActionPerformed(evt);
            }
        });
        getContentPane().add(JBFischl, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 130, 130));

        JBKeqing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Avatares/Keqing-Icon.png"))); // NOI18N
        getContentPane().add(JBKeqing, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 130, 130));

        JBMona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Avatares/Mona-Icon.png"))); // NOI18N
        JBMona.setPreferredSize(new java.awt.Dimension(161, 137));
        JBMona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMonaActionPerformed(evt);
            }
        });
        getContentPane().add(JBMona, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 130, 130));

        JBQiqi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Avatares/Qiqi-Icon.png"))); // NOI18N
        getContentPane().add(JBQiqi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 130, 130));

        JBVenti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Avatares/Venti-Icon.png"))); // NOI18N
        getContentPane().add(JBVenti, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 130, 130));

        JBXiangling.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Avatares/Xiangling-Icon.png"))); // NOI18N
        getContentPane().add(JBXiangling, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 130, 130));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Avatares/Zhongli-Icon.png"))); // NOI18N
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, 130, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/screen-5.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBBeidouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBeidouActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBBeidouActionPerformed

    private void JBMonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBMonaActionPerformed

    private void JBFischlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBFischlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBFischlActionPerformed

    private void JBBarbaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBarbaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBBarbaraActionPerformed

    private void JBBarbaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBBarbaraMouseClicked
        // TODO add your handling code here:
        FRMEleccionPersonajes.repaint();
    }//GEN-LAST:event_JBBarbaraMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBBarbara;
    private javax.swing.JButton JBBeidou;
    private javax.swing.JButton JBChongyun;
    private javax.swing.JButton JBDiluc;
    private javax.swing.JButton JBFischl;
    private javax.swing.JButton JBKeqing;
    private javax.swing.JButton JBMona;
    private javax.swing.JButton JBQiqi;
    private javax.swing.JButton JBSucrose;
    private javax.swing.JButton JBVenti;
    private javax.swing.JButton JBXiangling;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
